version: '3'

services:
  ### NGINX ################################################
  nginx:
    build: ./nginx
    container_name: nginx114
    privileged: true
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    links:
      - "php"
    volumes:
      # nginx默认配置文件
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # server
      - ./nginx/conf.d:/etc/nginx/conf.d
      # 项目代码
      - ../:/var/www/
      # nginx日志
      - ./logs/nginx/:/var/log/nginx/
    networks:
      backend:
        ipv4_address: ${NGINX_IP}

  ### MySQL ################################################
  mysql:
    image: mysql:5.7
    container_name: mysql57
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    privileged: true
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      backend:
        ipv4_address: ${MYSQL_IP}

  ### PHP ################################################
  php:
    build:
      context: ./php
    container_name: php7
    privileged: true
    cap_add:
      - SYS_PTRACE
    ports:
      - "9000:9000"
    depends_on:
      - "mysql"
      - "redis"
    extra_hosts:
      - "default.dev.com:${NGINX_IP}"
    volumes:
      # 项目代码
      - ../:/var/www/
      # php 配置文件
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
#      - ./php/config/conf.d:/usr/local/etc/php/conf.d
      # php-fpm 配置文件
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
      # php-fpm 日志
      - ./logs/php/:/var/log/php/
    networks:
      backend:
        ipv4_address: ${PHP_IP}

  ### Redis ################################################
  redis:
    image: redis
    container_name: redis5
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ${DATA_PATH}/redis:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      backend:
        ipv4_address: ${REDIS_IP}

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
